/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessHistoryRouteImport } from './routes/access-history'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ContentRouteImport } from './routes/content'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as ComplaintsIndexRouteImport } from './routes/complaints.index'
import { Route as ComplaintsIdRouteImport } from './routes/complaints.$id'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceCommissionsRouteImport } from './routes/finance.commissions'
import { Route as FinanceInvoicesRouteImport } from './routes/finance.invoices'
import { Route as FinanceOrganizationEarningsRouteImport } from './routes/finance.organization-earnings'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceProviderPayoutsRouteImport } from './routes/finance.provider-payouts'
import { Route as FinanceRefundsRouteImport } from './routes/finance.refunds'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinanceSubscriptionsRouteImport } from './routes/finance.subscriptions'
import { Route as FinanceTransactionsRouteImport } from './routes/finance.transactions'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as PetParentsIndexRouteImport } from './routes/pet-parents.index'
import { Route as PetParentsIdRouteImport } from './routes/pet-parents.$id'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCategoriesRouteImport } from './routes/services.categories'
import { Route as ServicesRequestsRouteImport } from './routes/services.requests'
import { Route as VerificationIndexRouteImport } from './routes/verification.index'
import { Route as VerificationIdRouteImport } from './routes/verification.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessHistoryRoute = AccessHistoryRouteImport.update({
  id: '/access-history',
  path: '/access-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIndexRoute = ComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsIdRoute = ComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCommissionsRoute = FinanceCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceOrganizationEarningsRoute =
  FinanceOrganizationEarningsRouteImport.update({
    id: '/organization-earnings',
    path: '/organization-earnings',
    getParentRoute: () => FinanceRoute,
  } as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceProviderPayoutsRoute = FinanceProviderPayoutsRouteImport.update({
  id: '/provider-payouts',
  path: '/provider-payouts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceRefundsRoute = FinanceRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSubscriptionsRoute = FinanceSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTransactionsRoute = FinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => FinanceRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PetParentsIndexRoute = PetParentsIndexRouteImport.update({
  id: '/pet-parents/',
  path: '/pet-parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetParentsIdRoute = PetParentsIdRouteImport.update({
  id: '/pet-parents/$id',
  path: '/pet-parents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoriesRoute = ServicesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRequestsRoute = ServicesRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ServicesRoute,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/verification/',
  path: '/verification/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationIdRoute = VerificationIdRouteImport.update({
  id: '/verification/$id',
  path: '/verification/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/communication': typeof CommunicationRoute
  '/content': typeof ContentRoute
  '/finance': typeof FinanceRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/finance/commissions': typeof FinanceCommissionsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/organization-earnings': typeof FinanceOrganizationEarningsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/provider-payouts': typeof FinanceProviderPayoutsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/pet-parents/$id': typeof PetParentsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/categories': typeof ServicesCategoriesRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/verification/$id': typeof VerificationIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pet-parents/': typeof PetParentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/communication': typeof CommunicationRoute
  '/content': typeof ContentRoute
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/finance/commissions': typeof FinanceCommissionsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/organization-earnings': typeof FinanceOrganizationEarningsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/provider-payouts': typeof FinanceProviderPayoutsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/pet-parents/$id': typeof PetParentsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/categories': typeof ServicesCategoriesRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/verification/$id': typeof VerificationIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/complaints': typeof ComplaintsIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/pet-parents': typeof PetParentsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/verification': typeof VerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-history': typeof AccessHistoryRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/communication': typeof CommunicationRoute
  '/content': typeof ContentRoute
  '/finance': typeof FinanceRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/complaints/$id': typeof ComplaintsIdRoute
  '/finance/commissions': typeof FinanceCommissionsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/organization-earnings': typeof FinanceOrganizationEarningsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/provider-payouts': typeof FinanceProviderPayoutsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/transactions': typeof FinanceTransactionsRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/pet-parents/$id': typeof PetParentsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/categories': typeof ServicesCategoriesRoute
  '/services/requests': typeof ServicesRequestsRoute
  '/verification/$id': typeof VerificationIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/complaints/': typeof ComplaintsIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/pet-parents/': typeof PetParentsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/verification/': typeof VerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-history'
    | '/analytics'
    | '/audit-logs'
    | '/communication'
    | '/content'
    | '/finance'
    | '/notifications'
    | '/promotions'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/bookings/$id'
    | '/complaints/$id'
    | '/finance/commissions'
    | '/finance/invoices'
    | '/finance/organization-earnings'
    | '/finance/payments'
    | '/finance/provider-payouts'
    | '/finance/refunds'
    | '/finance/reports'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/organizations/$id'
    | '/pet-parents/$id'
    | '/providers/$id'
    | '/services/categories'
    | '/services/requests'
    | '/verification/$id'
    | '/bookings/'
    | '/complaints/'
    | '/finance/'
    | '/organizations/'
    | '/pet-parents/'
    | '/providers/'
    | '/services/'
    | '/verification/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-history'
    | '/analytics'
    | '/audit-logs'
    | '/communication'
    | '/content'
    | '/notifications'
    | '/promotions'
    | '/reviews'
    | '/settings'
    | '/bookings/$id'
    | '/complaints/$id'
    | '/finance/commissions'
    | '/finance/invoices'
    | '/finance/organization-earnings'
    | '/finance/payments'
    | '/finance/provider-payouts'
    | '/finance/refunds'
    | '/finance/reports'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/organizations/$id'
    | '/pet-parents/$id'
    | '/providers/$id'
    | '/services/categories'
    | '/services/requests'
    | '/verification/$id'
    | '/bookings'
    | '/complaints'
    | '/finance'
    | '/organizations'
    | '/pet-parents'
    | '/providers'
    | '/services'
    | '/verification'
  id:
    | '__root__'
    | '/'
    | '/access-history'
    | '/analytics'
    | '/audit-logs'
    | '/communication'
    | '/content'
    | '/finance'
    | '/notifications'
    | '/promotions'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/bookings/$id'
    | '/complaints/$id'
    | '/finance/commissions'
    | '/finance/invoices'
    | '/finance/organization-earnings'
    | '/finance/payments'
    | '/finance/provider-payouts'
    | '/finance/refunds'
    | '/finance/reports'
    | '/finance/subscriptions'
    | '/finance/transactions'
    | '/organizations/$id'
    | '/pet-parents/$id'
    | '/providers/$id'
    | '/services/categories'
    | '/services/requests'
    | '/verification/$id'
    | '/bookings/'
    | '/complaints/'
    | '/finance/'
    | '/organizations/'
    | '/pet-parents/'
    | '/providers/'
    | '/services/'
    | '/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessHistoryRoute: typeof AccessHistoryRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CommunicationRoute: typeof CommunicationRoute
  ContentRoute: typeof ContentRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PromotionsRoute: typeof PromotionsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  BookingsIdRoute: typeof BookingsIdRoute
  ComplaintsIdRoute: typeof ComplaintsIdRoute
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  PetParentsIdRoute: typeof PetParentsIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  VerificationIdRoute: typeof VerificationIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ComplaintsIndexRoute: typeof ComplaintsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  PetParentsIndexRoute: typeof PetParentsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  VerificationIndexRoute: typeof VerificationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-history': {
      id: '/access-history'
      path: '/access-history'
      fullPath: '/access-history'
      preLoaderRoute: typeof AccessHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/': {
      id: '/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof ComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints/$id': {
      id: '/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof ComplaintsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/commissions': {
      id: '/finance/commissions'
      path: '/commissions'
      fullPath: '/finance/commissions'
      preLoaderRoute: typeof FinanceCommissionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/organization-earnings': {
      id: '/finance/organization-earnings'
      path: '/organization-earnings'
      fullPath: '/finance/organization-earnings'
      preLoaderRoute: typeof FinanceOrganizationEarningsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/provider-payouts': {
      id: '/finance/provider-payouts'
      path: '/provider-payouts'
      fullPath: '/finance/provider-payouts'
      preLoaderRoute: typeof FinanceProviderPayoutsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/refunds': {
      id: '/finance/refunds'
      path: '/refunds'
      fullPath: '/finance/refunds'
      preLoaderRoute: typeof FinanceRefundsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/subscriptions': {
      id: '/finance/subscriptions'
      path: '/subscriptions'
      fullPath: '/finance/subscriptions'
      preLoaderRoute: typeof FinanceSubscriptionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/transactions': {
      id: '/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof FinanceTransactionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-parents/': {
      id: '/pet-parents/'
      path: '/pet-parents'
      fullPath: '/pet-parents/'
      preLoaderRoute: typeof PetParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-parents/$id': {
      id: '/pet-parents/$id'
      path: '/pet-parents/$id'
      fullPath: '/pet-parents/$id'
      preLoaderRoute: typeof PetParentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/categories': {
      id: '/services/categories'
      path: '/categories'
      fullPath: '/services/categories'
      preLoaderRoute: typeof ServicesCategoriesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/requests': {
      id: '/services/requests'
      path: '/requests'
      fullPath: '/services/requests'
      preLoaderRoute: typeof ServicesRequestsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/verification/': {
      id: '/verification/'
      path: '/verification'
      fullPath: '/verification/'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/$id': {
      id: '/verification/$id'
      path: '/verification/$id'
      fullPath: '/verification/$id'
      preLoaderRoute: typeof VerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceCommissionsRoute: typeof FinanceCommissionsRoute
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinanceOrganizationEarningsRoute: typeof FinanceOrganizationEarningsRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceProviderPayoutsRoute: typeof FinanceProviderPayoutsRoute
  FinanceRefundsRoute: typeof FinanceRefundsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceSubscriptionsRoute: typeof FinanceSubscriptionsRoute
  FinanceTransactionsRoute: typeof FinanceTransactionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCommissionsRoute: FinanceCommissionsRoute,
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinanceOrganizationEarningsRoute: FinanceOrganizationEarningsRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceProviderPayoutsRoute: FinanceProviderPayoutsRoute,
  FinanceRefundsRoute: FinanceRefundsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceSubscriptionsRoute: FinanceSubscriptionsRoute,
  FinanceTransactionsRoute: FinanceTransactionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface ServicesRouteChildren {
  ServicesCategoriesRoute: typeof ServicesCategoriesRoute
  ServicesRequestsRoute: typeof ServicesRequestsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoriesRoute: ServicesCategoriesRoute,
  ServicesRequestsRoute: ServicesRequestsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessHistoryRoute: AccessHistoryRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditLogsRoute: AuditLogsRoute,
  CommunicationRoute: CommunicationRoute,
  ContentRoute: ContentRoute,
  FinanceRoute: FinanceRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PromotionsRoute: PromotionsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  BookingsIdRoute: BookingsIdRoute,
  ComplaintsIdRoute: ComplaintsIdRoute,
  OrganizationsIdRoute: OrganizationsIdRoute,
  PetParentsIdRoute: PetParentsIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  VerificationIdRoute: VerificationIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ComplaintsIndexRoute: ComplaintsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  PetParentsIndexRoute: PetParentsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  VerificationIndexRoute: VerificationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
